# 1. Setup Paths and Source URLs

In [6]:
from pathlib import Path

import polars as pl

root = Path.cwd().resolve()
data_dir = root/ "data"
data_dir.mkdir(parents=True, exist_ok=True)

daioe_source: str = (
    "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_years/development/"
    "data/daioe_scb_years_all_levels.parquet"
)

scb_source: str = (
        "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_months_v2/daioe_pull/"
        "data/scb_months.parquet"

)

# 2. Load DAIOE and SCB Lazily

In [7]:
daioe_lf = pl.scan_parquet(
    daioe_source,
)

scb_lf = pl.scan_parquet(
    scb_source,
)

# 3. Quick Sanity Checks

Data preview

In [8]:
print(daioe_lf.head(5).collect())

shape: (5, 65)
┌───────┬───────────┬───────┬───────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ level ┆ ssyk_code ┆ age   ┆ sex   ┆ … ┆ daioe_lngmod ┆ daioe_transl ┆ daioe_speech ┆ daioe_genai │
│ ---   ┆ ---       ┆ ---   ┆ ---   ┆   ┆ _Level_Expos ┆ at_Level_Exp ┆ rec_Level_Ex ┆ _Level_Expo │
│ str   ┆ str       ┆ str   ┆ str   ┆   ┆ ure          ┆ osure        ┆ posure       ┆ sure        │
│       ┆           ┆       ┆       ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│       ┆           ┆       ┆       ┆   ┆ i8           ┆ i8           ┆ i8           ┆ i8          │
╞═══════╪═══════════╪═══════╪═══════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ SSYK3 ┆ 732       ┆ 30-34 ┆ men   ┆ … ┆ 2            ┆ 3            ┆ 2            ┆ 2           │
│ SSYK3 ┆ 129       ┆ 50-54 ┆ men   ┆ … ┆ 4            ┆ 4            ┆ 4            ┆ 4           │
│ SSYK3 ┆ 152       ┆ 40-44 ┆ men   ┆ … ┆ 4            ┆ 4            ┆ 4            ┆ 4           │
│ SSYK3 ┆ 512       ┆ 60-64 ┆ women ┆ … ┆ 2            ┆ 2            ┆ 2            ┆ 2           │
│ SSYK3 ┆ 218       ┆ 55-59 ┆ men   ┆ … ┆ 3            ┆ 3            ┆ 3            ┆ 4           │
└───────┴───────────┴───────┴───────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [9]:
print(scb_lf.head(5).collect())

shape: (5, 5)
┌────────┬─────┬──────────┬───────┬────────────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ occupation │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆ ---        │
│ str    ┆ str ┆ str      ┆ str   ┆ str        │
╞════════╪═════╪══════════╪═══════╪════════════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 135.1 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Feb ┆ 125.6 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Mar ┆ 120.2 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Apr ┆ 141.6 ┆ Managers   │
│ 1      ┆ men ┆ 2015-May ┆ 137.1 ┆ Managers   │
└────────┴─────┴──────────┴───────┴────────────┘

In [ ]:
scb_lf_clean = scb_lf\
    .filter(pl.col("code_1").str.starts_with(0).not_())\
        .with_columns(
    pl.col("month")
      .str.extract(r"^(\d{4})", 1)
      .cast(pl.Int64)
      .alias("year"),
)


print(scb_lf_clean.limit(10).collect())

shape: (10, 6)
┌────────┬─────┬──────────┬───────┬────────────┬──────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ occupation ┆ year │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆ ---        ┆ ---  │
│ str    ┆ str ┆ str      ┆ str   ┆ str        ┆ i64  │
╞════════╪═════╪══════════╪═══════╪════════════╪══════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 135.1 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Feb ┆ 125.6 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Mar ┆ 120.2 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Apr ┆ 141.6 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-May ┆ 137.1 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Jun ┆ 112.8 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Jul ┆ 142.5 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Aug ┆ 137.1 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Sep ┆ 120.7 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Oct ┆ 150.0 ┆ Managers   ┆ 2015 │
└────────┴─────┴──────────┴───────┴────────────┴──────┘

# 4. Compute 1-month, 3-months and 6-months Change

In [24]:

change_keys = [col for col in scb_lf_clean.collect_schema().names() if col != "value"]
time_col = "month"
group_keys = [col for col in change_keys if col != time_col]

def _pct_chg(current: pl.Expr, shifted: pl.Expr) -> pl.Expr:
    return (
        pl.when(shifted.is_not_null() & shifted.ne(0))
        .then((current / shifted - 1) * 100)
        .otherwise(None)
    )


raw_emp = pl.col("value")
emp = pl.col("emp_count")

scb_lazy_lf_changes = (
    scb_lf_clean
    .with_columns(pl.col("value").replace("..", None).cast(pl.Float64))
    .group_by(change_keys)
    .agg(raw_emp.sum().alias("emp_count"))
    .with_columns(
        pl.col(time_col).str.strptime(pl.Date, "%Y-%b", strict=False).alias("_month_date"),
    )
    # Pre-compute shifted values
    .with_columns(
        emp.shift(1).over(group_keys, order_by="_month_date").alias("_emp_1m"),
        emp.shift(3).over(group_keys, order_by="_month_date").alias("_emp_3m"),
        emp.shift(6).over(group_keys, order_by="_month_date").alias("_emp_6m"),
    )
    # Absolute and percentage changes
    .with_columns(
        (emp - pl.col("_emp_1m")).alias("chg_1m"),
        (emp - pl.col("_emp_3m")).alias("chg_3m"),
        (emp - pl.col("_emp_6m")).alias("chg_6m"),
        _pct_chg(emp, pl.col("_emp_1m")).alias("pct_chg_1m"),
        _pct_chg(emp, pl.col("_emp_3m")).alias("pct_chg_3m"),
        _pct_chg(emp, pl.col("_emp_6m")).alias("pct_chg_6m"),
    )
    .drop("_month_date", "_emp_1m", "_emp_3m", "_emp_6m")
    .sort(
    by=[
        "code_1",
        "sex",
        "occupation",
        pl.col("month").str.strptime(pl.Date, "%Y-%b", strict=False),
    ],
)
)

scb_lazy_lf_changes.collect_schema()

Schema([('code_1', String),
        ('sex', String),
        ('month', String),
        ('occupation', String),
        ('year', Int64),
        ('emp_count', Float64),
        ('chg_1m', Float64),
        ('chg_3m', Float64),
        ('chg_6m', Float64),
        ('pct_chg_1m', Float64),
        ('pct_chg_3m', Float64),
        ('pct_chg_6m', Float64)])

In [25]:
scb_lazy_lf_changes.head(10).collect()

shape: (10, 12)
┌────────┬─────┬──────────┬────────────┬───┬────────┬────────────┬────────────┬────────────┐
│ code_1 ┆ sex ┆ month    ┆ occupation ┆ … ┆ chg_6m ┆ pct_chg_1m ┆ pct_chg_3m ┆ pct_chg_6m │
│ ---    ┆ --- ┆ ---      ┆ ---        ┆   ┆ ---    ┆ ---        ┆ ---        ┆ ---        │
│ str    ┆ str ┆ str      ┆ str        ┆   ┆ f64    ┆ f64        ┆ f64        ┆ f64        │
╞════════╪═════╪══════════╪════════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 1      ┆ men ┆ 2015-Jan ┆ Managers   ┆ … ┆ null   ┆ null       ┆ null       ┆ null       │
│ 1      ┆ men ┆ 2015-Feb ┆ Managers   ┆ … ┆ null   ┆ -5.776256  ┆ null       ┆ null       │
│ 1      ┆ men ┆ 2015-Mar ┆ Managers   ┆ … ┆ null   ┆ -4.603828  ┆ null       ┆ null       │
│ 1      ┆ men ┆ 2015-Apr ┆ Managers   ┆ … ┆ null   ┆ 14.83363   ┆ 3.219178   ┆ null       │
│ 1      ┆ men ┆ 2015-May ┆ Managers   ┆ … ┆ null   ┆ -1.017474  ┆ 8.432275   ┆ null       │
│ 1      ┆ men ┆ 2015-Jun ┆ Managers   ┆ … ┆ null   ┆ -16.826816 ┆ -5.461011  ┆ null       │
│ 1      ┆ men ┆ 2015-Jul ┆ Managers   ┆ … ┆ 17.4   ┆ 22.353573  ┆ 0.729927   ┆ 3.972603   │
│ 1      ┆ men ┆ 2015-Aug ┆ Managers   ┆ … ┆ 31.1   ┆ -2.547211  ┆ -0.826816  ┆ 7.53574    │
│ 1      ┆ men ┆ 2015-Sep ┆ Managers   ┆ … ┆ 1.4    ┆ -10.973411 ┆ 6.152606   ┆ 0.355601   │
│ 1      ┆ men ┆ 2015-Oct ┆ Managers   ┆ … ┆ 33.3   ┆ 22.854973  ┆ 6.587615   ┆ 7.365627   │
└────────┴─────┴──────────┴────────────┴───┴────────┴────────────┴────────────┴────────────┘

# 5. Prepare DAIOE Level-1 Aggregates

In [19]:
weighted_daioe = daioe_lf\
    .filter(
        pl.col("level") == "SSYK1",
        )\
        .select(
            pl.col(["level", "ssyk_code", "year", "weight_sum"]),
            pl.col("^daioe_.*$"),
            pl.col("^pctl_daioe_.*$"),
            )\
            .group_by(["level", "ssyk_code", "year"])\
                .agg([
                    pl.col("weight_sum").mean().cast(pl.Int64),
                    pl.col("^daioe_.*$").mean(),
                    pl.col("^pctl_daioe_.*$").mean(),
                    ])

weighted_daioe.limit(10).collect()

shape: (10, 59)
┌───────┬───────────┬──────┬────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ level ┆ ssyk_code ┆ year ┆ weight_sum ┆ … ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe │
│ ---   ┆ ---       ┆ ---  ┆ ---        ┆   ┆ lngmod_wavg ┆ translat_wa ┆ speechrec_w ┆ _genai_wav │
│ str   ┆ str       ┆ i64  ┆ i64        ┆   ┆ ---         ┆ vg          ┆ avg         ┆ g          │
│       ┆           ┆      ┆            ┆   ┆ f64         ┆ ---         ┆ ---         ┆ ---        │
│       ┆           ┆      ┆            ┆   ┆             ┆ f64         ┆ f64         ┆ f64        │
╞═══════╪═══════════╪══════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ SSYK1 ┆ 5         ┆ 2022 ┆ 1006464    ┆ … ┆ 50.0        ┆ 50.0        ┆ 50.0        ┆ 50.0       │
│ SSYK1 ┆ 8         ┆ 2024 ┆ 347858     ┆ … ┆ 12.5        ┆ 25.0        ┆ 25.0        ┆ 12.5       │
│ SSYK1 ┆ 9         ┆ 2016 ┆ 235399     ┆ … ┆ 0.0         ┆ 0.0         ┆ 12.5        ┆ 0.0        │
│ SSYK1 ┆ 2         ┆ 2015 ┆ 973635     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 100.0      │
│ SSYK1 ┆ 7         ┆ 2024 ┆ 438278     ┆ … ┆ 25.0        ┆ 12.5        ┆ 0.0         ┆ 37.5       │
│ SSYK1 ┆ 2         ┆ 2020 ┆ 1124063    ┆ … ┆ 100.0       ┆ 87.5        ┆ 87.5        ┆ 100.0      │
│ SSYK1 ┆ 1         ┆ 2015 ┆ 276948     ┆ … ┆ 75.0        ┆ 75.0        ┆ 75.0        ┆ 75.0       │
│ SSYK1 ┆ 6         ┆ 2017 ┆ 34657      ┆ … ┆ 37.5        ┆ 37.5        ┆ 37.5        ┆ 12.5       │
│ SSYK1 ┆ 4         ┆ 2023 ┆ 401274     ┆ … ┆ 87.5        ┆ 100.0       ┆ 100.0       ┆ 87.5       │
│ SSYK1 ┆ 6         ┆ 2016 ┆ 33827      ┆ … ┆ 37.5        ┆ 37.5        ┆ 37.5        ┆ 12.5       │
└───────┴───────────┴──────┴────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘