# 1. Setup Paths and Source URLs

Define the working data directory and the remote parquet sources used throughout the notebook.

In [1]:
from pathlib import Path

import polars as pl

root = Path.cwd().resolve()
data_dir = root/ "data"
data_dir.mkdir(parents=True, exist_ok=True)

daioe_source: str = (
    "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_years/development/"
    "data/daioe_scb_years_all_levels.parquet"
)

scb_source: str = (
        "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_months_v2/daioe_pull/"
        "data/scb_months.parquet"

)

def _pct_chg(current: pl.Expr, shifted: pl.Expr) -> pl.Expr:
    return (
        pl.when(shifted.is_not_null() & shifted.ne(0))
        .then((current / shifted - 1) * 100)
        .otherwise(None)
    )

# 2. Load DAIOE and SCB Lazily

Read both datasets as lazy Polars frames so the transformations can stay efficient until collection or export.

In [2]:
daioe_lf = pl.scan_parquet(
    daioe_source,
)

scb_lf = pl.scan_parquet(
    scb_source,
)

# 3. Quick Sanity Checks

Preview both inputs to confirm the expected columns, types, and general structure before transforming them.

In [3]:
print(daioe_lf.head(5).collect())

shape: (5, 65)
┌───────┬───────────┬───────┬───────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ level ┆ ssyk_code ┆ age   ┆ sex   ┆ … ┆ daioe_lngmod ┆ daioe_transl ┆ daioe_speech ┆ daioe_genai │
│ ---   ┆ ---       ┆ ---   ┆ ---   ┆   ┆ _Level_Expos ┆ at_Level_Exp ┆ rec_Level_Ex ┆ _Level_Expo │
│ str   ┆ str       ┆ str   ┆ str   ┆   ┆ ure          ┆ osure        ┆ posure       ┆ sure        │
│       ┆           ┆       ┆       ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│       ┆           ┆       ┆       ┆   ┆ i8           ┆ i8           ┆ i8           ┆ i8          │
╞═══════╪═══════════╪═══════╪═══════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ SSYK3 ┆ 137       ┆ 16-24 ┆ men   ┆ … ┆ 3            ┆ 3            ┆ 3            ┆ 3           │
│ SSYK3 ┆ 344       ┆ 60-64 ┆ women ┆ … ┆ 4            ┆ 5            ┆ 5            ┆ 4           │
│ SSYK3 ┆ 421       ┆ 25-29 ┆ men   ┆ … ┆ 4            ┆ 5            ┆ 5            ┆ 4           │
│ SSYK3 ┆ 817       ┆ 25-29 ┆ women ┆ … ┆ 1            ┆ 3            ┆ 1            ┆ 1           │
│ SSYK3 ┆ 173       ┆ 35-39 ┆ women ┆ … ┆ 3            ┆ 3            ┆ 3            ┆ 3           │
└───────┴───────────┴───────┴───────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [4]:
print(scb_lf.head(5).collect())

shape: (5, 5)
┌────────┬─────┬──────────┬───────┬────────────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ occupation │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆ ---        │
│ str    ┆ str ┆ str      ┆ str   ┆ str        │
╞════════╪═════╪══════════╪═══════╪════════════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 135.1 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Feb ┆ 125.6 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Mar ┆ 120.2 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Apr ┆ 141.6 ┆ Managers   │
│ 1      ┆ men ┆ 2015-May ┆ 137.1 ┆ Managers   │
└────────┴─────┴──────────┴───────┴────────────┘

In [5]:
scb_lf_clean = scb_lf\
    .filter(pl.col("code_1").str.starts_with(0).not_())\
        .with_columns(
    pl.col("month")
      .str.extract(r"^(\d{4})", 1)
      .cast(pl.Int64)
      .alias("year"),
)


print(scb_lf_clean.limit(10).collect())

shape: (10, 6)
┌────────┬─────┬──────────┬───────┬────────────┬──────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ occupation ┆ year │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆ ---        ┆ ---  │
│ str    ┆ str ┆ str      ┆ str   ┆ str        ┆ i64  │
╞════════╪═════╪══════════╪═══════╪════════════╪══════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 135.1 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Feb ┆ 125.6 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Mar ┆ 120.2 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Apr ┆ 141.6 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-May ┆ 137.1 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Jun ┆ 112.8 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Jul ┆ 142.5 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Aug ┆ 137.1 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Sep ┆ 120.7 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Oct ┆ 150.0 ┆ Managers   ┆ 2015 │
└────────┴─────┴──────────┴───────┴────────────┴──────┘

# 4. Compute 1-month, 3-months and 6-months Change

Clean the SCB monthly employment counts and create short-run absolute and percentage change measures by occupation and sex.

In [6]:

change_keys = [col for col in scb_lf_clean.collect_schema().names() if col != "value"]
time_col = "month"
group_keys = [col for col in change_keys if col != time_col]

raw_emp = pl.col("value")
emp = pl.col("emp_count")

scb_lazy_lf_changes = (
    scb_lf_clean
    .with_columns(pl.col("value").cast(pl.Float64, strict=False))
    .group_by(change_keys)
    .agg(raw_emp.sum().alias("emp_count"))
    .with_columns(
        pl.col(time_col).str.strptime(pl.Date, "%Y-%b", strict=False).alias("_month_date"),
    )
    # Pre-compute shifted values
    .with_columns(
        emp.shift(1).over(group_keys, order_by="_month_date").alias("_emp_1m"),
        emp.shift(3).over(group_keys, order_by="_month_date").alias("_emp_3m"),
        emp.shift(6).over(group_keys, order_by="_month_date").alias("_emp_6m"),
    )
    # Absolute and percentage changes
    .with_columns(
        (emp - pl.col("_emp_1m")).alias("chg_1m"),
        (emp - pl.col("_emp_3m")).alias("chg_3m"),
        (emp - pl.col("_emp_6m")).alias("chg_6m"),
        _pct_chg(emp, pl.col("_emp_1m")).alias("pct_chg_1m"),
        _pct_chg(emp, pl.col("_emp_3m")).alias("pct_chg_3m"),
        _pct_chg(emp, pl.col("_emp_6m")).alias("pct_chg_6m"),
    )
    .sort(
        by=[
            "code_1",
            "sex",
            "occupation",
            "_month_date",
        ],
    )
    .drop("_month_date", "_emp_1m", "_emp_3m", "_emp_6m")
)

scb_lazy_lf_changes.collect_schema()

Schema([('code_1', String),
        ('sex', String),
        ('month', String),
        ('occupation', String),
        ('year', Int64),
        ('emp_count', Float64),
        ('chg_1m', Float64),
        ('chg_3m', Float64),
        ('chg_6m', Float64),
        ('pct_chg_1m', Float64),
        ('pct_chg_3m', Float64),
        ('pct_chg_6m', Float64)])

In [7]:
scb_lazy_lf_changes.head(10).collect()

shape: (10, 12)
┌────────┬─────┬──────────┬────────────┬───┬────────┬────────────┬────────────┬────────────┐
│ code_1 ┆ sex ┆ month    ┆ occupation ┆ … ┆ chg_6m ┆ pct_chg_1m ┆ pct_chg_3m ┆ pct_chg_6m │
│ ---    ┆ --- ┆ ---      ┆ ---        ┆   ┆ ---    ┆ ---        ┆ ---        ┆ ---        │
│ str    ┆ str ┆ str      ┆ str        ┆   ┆ f64    ┆ f64        ┆ f64        ┆ f64        │
╞════════╪═════╪══════════╪════════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 1      ┆ men ┆ 2015-Jan ┆ Managers   ┆ … ┆ null   ┆ null       ┆ null       ┆ null       │
│ 1      ┆ men ┆ 2015-Feb ┆ Managers   ┆ … ┆ null   ┆ -5.776256  ┆ null       ┆ null       │
│ 1      ┆ men ┆ 2015-Mar ┆ Managers   ┆ … ┆ null   ┆ -4.603828  ┆ null       ┆ null       │
│ 1      ┆ men ┆ 2015-Apr ┆ Managers   ┆ … ┆ null   ┆ 14.83363   ┆ 3.219178   ┆ null       │
│ 1      ┆ men ┆ 2015-May ┆ Managers   ┆ … ┆ null   ┆ -1.017474  ┆ 8.432275   ┆ null       │
│ 1      ┆ men ┆ 2015-Jun ┆ Managers   ┆ … ┆ null   ┆ -16.826816 ┆ -5.461011  ┆ null       │
│ 1      ┆ men ┆ 2015-Jul ┆ Managers   ┆ … ┆ 17.4   ┆ 22.353573  ┆ 0.729927   ┆ 3.972603   │
│ 1      ┆ men ┆ 2015-Aug ┆ Managers   ┆ … ┆ 31.1   ┆ -2.547211  ┆ -0.826816  ┆ 7.53574    │
│ 1      ┆ men ┆ 2015-Sep ┆ Managers   ┆ … ┆ 1.4    ┆ -10.973411 ┆ 6.152606   ┆ 0.355601   │
│ 1      ┆ men ┆ 2015-Oct ┆ Managers   ┆ … ┆ 33.3   ┆ 22.854973  ┆ 6.587615   ┆ 7.365627   │
└────────┴─────┴──────────┴────────────┴───┴────────┴────────────┴────────────┴────────────┘

# 5. Prepare DAIOE Level-1 Aggregates

Filter the DAIOE data to SSYK1 and aggregate yearly exposure metrics so they can be joined onto the SCB panel.

In [8]:
weighted_daioe = daioe_lf\
    .filter(
        pl.col("level") == "SSYK1",
        )\
        .select(
            pl.col(["level", "ssyk_code", "year", "weight_sum"]),
            pl.col("^daioe_.*$"),
            pl.col("^pctl_daioe_.*$"),
            )\
            .group_by(["level", "ssyk_code", "year"])\
                .agg([
                    pl.col("weight_sum").mean().cast(pl.Int64),
                    pl.col("^daioe_.*$").mean(),
                    pl.col("^pctl_daioe_.*$").mean(),
                    ])

weighted_daioe.limit(10).collect()

shape: (10, 59)
┌───────┬───────────┬──────┬────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ level ┆ ssyk_code ┆ year ┆ weight_sum ┆ … ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe │
│ ---   ┆ ---       ┆ ---  ┆ ---        ┆   ┆ lngmod_wavg ┆ translat_wa ┆ speechrec_w ┆ _genai_wav │
│ str   ┆ str       ┆ i64  ┆ i64        ┆   ┆ ---         ┆ vg          ┆ avg         ┆ g          │
│       ┆           ┆      ┆            ┆   ┆ f64         ┆ ---         ┆ ---         ┆ ---        │
│       ┆           ┆      ┆            ┆   ┆             ┆ f64         ┆ f64         ┆ f64        │
╞═══════╪═══════════╪══════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ SSYK1 ┆ 3         ┆ 2014 ┆ 548032     ┆ … ┆ 87.5        ┆ 50.0        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 5         ┆ 2015 ┆ 939548     ┆ … ┆ 37.5        ┆ 37.5        ┆ 37.5        ┆ 37.5       │
│ SSYK1 ┆ 6         ┆ 2022 ┆ 36769      ┆ … ┆ 25.0        ┆ 25.0        ┆ 25.0        ┆ 25.0       │
│ SSYK1 ┆ 7         ┆ 2023 ┆ 445323     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 4         ┆ 2015 ┆ 347608     ┆ … ┆ 62.5        ┆ 62.5        ┆ 62.5        ┆ 50.0       │
│ SSYK1 ┆ 7         ┆ 2018 ┆ 402690     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 3         ┆ 2024 ┆ 670251     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 3         ┆ 2015 ┆ 553719     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 8         ┆ 2021 ┆ 309692     ┆ … ┆ 12.5        ┆ 12.5        ┆ 12.5        ┆ 12.5       │
│ SSYK1 ┆ 1         ┆ 2023 ┆ 333614     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
└───────┴───────────┴──────┴────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

# 6. Align DAIOE Years to SCB Coverage

Extend the yearly DAIOE table forward to match the latest year present in the SCB data.

In [9]:
## Here I extend the years to Latest according to the pulled SCB data (2024, yearly)

base = weighted_daioe

# Extend years to latest available in SCB data (2024, yearly)
DAIOE_MAX_YEAR = base.select(pl.max("year")).collect().item()

SCB_MAX_YEAR = scb_lazy_lf_changes.select(pl.max("year")).collect().item()

missing_years = list(range(DAIOE_MAX_YEAR + 1, SCB_MAX_YEAR + 1))

daioe_lazy_lf_extended = (
    base
    if not missing_years
    else pl.concat(
        [
            base,
            base
            .filter(pl.col("year") == DAIOE_MAX_YEAR)
            .drop("year")
            .join(pl.LazyFrame({"year": missing_years}), how="cross")
            .select(base.collect_schema().names()),
        ],
        how="vertical",
    )
)

In [10]:
daioe_lazy_lf_extended.filter(pl.col("year") == SCB_MAX_YEAR).limit(10).collect()

shape: (9, 59)
┌───────┬───────────┬──────┬────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ level ┆ ssyk_code ┆ year ┆ weight_sum ┆ … ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe │
│ ---   ┆ ---       ┆ ---  ┆ ---        ┆   ┆ lngmod_wavg ┆ translat_wa ┆ speechrec_w ┆ _genai_wav │
│ str   ┆ str       ┆ i64  ┆ i64        ┆   ┆ ---         ┆ vg          ┆ avg         ┆ g          │
│       ┆           ┆      ┆            ┆   ┆ f64         ┆ ---         ┆ ---         ┆ ---        │
│       ┆           ┆      ┆            ┆   ┆             ┆ f64         ┆ f64         ┆ f64        │
╞═══════╪═══════════╪══════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ SSYK1 ┆ 8         ┆ 2026 ┆ 347858     ┆ … ┆ 12.5        ┆ 12.5        ┆ 12.5        ┆ 12.5       │
│ SSYK1 ┆ 2         ┆ 2026 ┆ 1320814    ┆ … ┆ 62.5        ┆ 50.0        ┆ 50.0        ┆ 62.5       │
│ SSYK1 ┆ 9         ┆ 2026 ┆ 302501     ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0        │
│ SSYK1 ┆ 6         ┆ 2026 ┆ 49511      ┆ … ┆ 25.0        ┆ 25.0        ┆ 25.0        ┆ 25.0       │
│ SSYK1 ┆ 1         ┆ 2026 ┆ 356245     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 7         ┆ 2026 ┆ 438278     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
│ SSYK1 ┆ 4         ┆ 2026 ┆ 392453     ┆ … ┆ 50.0        ┆ 62.5        ┆ 62.5        ┆ 50.0       │
│ SSYK1 ┆ 5         ┆ 2026 ┆ 1092837    ┆ … ┆ 37.5        ┆ 37.5        ┆ 37.5        ┆ 37.5       │
│ SSYK1 ┆ 3         ┆ 2026 ┆ 670251     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 87.5       │
└───────┴───────────┴──────┴────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

# 7. Merge SCB Monthly Data with the DAIOE Weights

Join the monthly SCB employment panel with the yearly DAIOE features using the shared occupation code and year.

In [11]:
scb_months_lf =scb_lazy_lf_changes\
                .join(
                    daioe_lazy_lf_extended,
                    left_on=["code_1", "year"],
                    right_on=["ssyk_code", "year"],
                    how = "left",
                )\
                    .drop("level")

scb_months_lf.limit(10).collect()

shape: (10, 68)
┌────────┬───────┬──────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ code_1 ┆ sex   ┆ month    ┆ occupation  ┆ … ┆ pctl_daioe_ ┆ pctl_daioe ┆ pctl_daioe ┆ pctl_daioe │
│ ---    ┆ ---   ┆ ---      ┆ ---         ┆   ┆ lngmod_wavg ┆ _translat_ ┆ _speechrec ┆ _genai_wav │
│ str    ┆ str   ┆ str      ┆ str         ┆   ┆ ---         ┆ wavg       ┆ _wavg      ┆ g          │
│        ┆       ┆          ┆             ┆   ┆ f64         ┆ ---        ┆ ---        ┆ ---        │
│        ┆       ┆          ┆             ┆   ┆             ┆ f64        ┆ f64        ┆ f64        │
╞════════╪═══════╪══════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2      ┆ men   ┆ 2024-Aug ┆ Occupations ┆ … ┆ 62.5        ┆ 50.0       ┆ 50.0       ┆ 62.5       │
│        ┆       ┆          ┆ requiring   ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ advanced…   ┆   ┆             ┆            ┆            ┆            │
│ 6      ┆ women ┆ 2021-Sep ┆ Agricultura ┆ … ┆ 25.0        ┆ 25.0       ┆ 25.0       ┆ 25.0       │
│        ┆       ┆          ┆ l, horticul ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ tural, f…   ┆   ┆             ┆            ┆            ┆            │
│ 4      ┆ women ┆ 2023-Apr ┆ Administrat ┆ … ┆ 50.0        ┆ 62.5       ┆ 62.5       ┆ 50.0       │
│        ┆       ┆          ┆ ion and     ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ customer    ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ se…         ┆   ┆             ┆            ┆            ┆            │
│ 7      ┆ women ┆ 2025-Jun ┆ Building    ┆ … ┆ 87.5        ┆ 87.5       ┆ 87.5       ┆ 87.5       │
│        ┆       ┆          ┆ and manufac ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ turing wor… ┆   ┆             ┆            ┆            ┆            │
│ 1      ┆ men   ┆ 2022-Mar ┆ Managers    ┆ … ┆ 87.5        ┆ 87.5       ┆ 87.5       ┆ 87.5       │
│ 5      ┆ women ┆ 2015-Jul ┆ Service,    ┆ … ┆ 37.5        ┆ 37.5       ┆ 37.5       ┆ 37.5       │
│        ┆       ┆          ┆ care and    ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ shop sales  ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ w…          ┆   ┆             ┆            ┆            ┆            │
│ 8      ┆ women ┆ 2024-Nov ┆ Mechanical  ┆ … ┆ 12.5        ┆ 12.5       ┆ 12.5       ┆ 12.5       │
│        ┆       ┆          ┆ manufacturi ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ ng and t…   ┆   ┆             ┆            ┆            ┆            │
│ 9      ┆ men   ┆ 2025-Nov ┆ Elementary  ┆ … ┆ 0.0         ┆ 0.0        ┆ 0.0        ┆ 0.0        │
│        ┆       ┆          ┆ occupations ┆   ┆             ┆            ┆            ┆            │
│ 2      ┆ men   ┆ 2022-Sep ┆ Occupations ┆ … ┆ 62.5        ┆ 50.0       ┆ 50.0       ┆ 62.5       │
│        ┆       ┆          ┆ requiring   ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ advanced…   ┆   ┆             ┆            ┆            ┆            │
│ 5      ┆ men   ┆ 2026-Jan ┆ Service,    ┆ … ┆ 37.5        ┆ 37.5       ┆ 37.5       ┆ 37.5       │
│        ┆       ┆          ┆ care and    ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ shop sales  ┆   ┆             ┆            ┆            ┆            │
│        ┆       ┆          ┆ w…          ┆   ┆             ┆            ┆            ┆            │
└────────┴───────┴──────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

# 8. Export the Cleaned Monthly Output

Write the final merged monthly dataset to parquet for downstream analysis.

In [12]:
scb_months_lf.sink_parquet(data_dir / "scb_months_lvl1.parquet")